function isValidEmail(e) { return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e) }
function getStrength(p) { if (!p) return null; var s = 0; if (p.length >= 8) s++; if (/[A-Z]/.test(p)) s++; if (/[0-9]/.test(p)) s++; if (/[^A-Za-z0-9]/.test(p)) s++; return s <= 1 ? 'weak' : s === 2 ? 'fair' : s === 3 ? 'good' : 'strong' }
var strengthLabels = { weak: 'Weak', fair: 'Fair', good: 'Good', strong: 'Strong' };
function showError(el, msg) { el.querySelector('span').textContent = msg; el.classList.remove('hidden') }
function hideError(el) { el.classList.add('hidden'); el.querySelector('span').textContent = '' }
function togglePass(id, btn) { var i = document.getElementById(id); var p = i.type === 'password'; i.type = p ? 'text' : 'password'; btn.querySelector('.eye-open').classList.toggle('hidden', p); btn.querySelector('.eye-closed').classList.toggle('hidden', !p) }
function updateStrength(iId, cId, fId, tId) { var p = document.getElementById(iId).value; var c = document.getElementById(cId); var f = document.getElementById(fId); var t = document.getElementById(tId); if (!p) { c.classList.add('hidden'); return } var s = getStrength(p); c.classList.remove('hidden'); f.className = 'strength-fill ' + s; t.className = 'strength-text ' + s; t.textContent = 'Password strength: ' + strengthLabels[s] }
function showView(v) { ['login', 'signup', 'forgot'].forEach(function (x) { document.getElementById(x + '-view').classList.add('hidden') }); document.getElementById(v + '-view').classList.remove('hidden'); document.querySelectorAll('#auth-container form').forEach(function (f) { f.reset() }); document.querySelectorAll('#auth-container .error-message').forEach(function (e) { e.classList.add('hidden') }); document.querySelectorAll('#auth-container .success-message').forEach(function (e) { e.classList.add('hidden') }); document.querySelectorAll('#auth-container .password-strength').forEach(function (e) { e.classList.add('hidden') }); document.querySelectorAll('#auth-container input.error').forEach(function (e) { e.classList.remove('error') }) }
var currentUserEmail = '';
function showDashboard(email) { currentUserEmail = email; document.getElementById('auth-container').classList.add('hidden'); document.getElementById('dashboard-wrapper').classList.remove('hidden'); document.body.classList.add('dashboard-active'); var name = email ? email.split('@')[0] : 'User'; name = name.charAt(0).toUpperCase() + name.slice(1); document.getElementById('dashboard-username').textContent = name; document.getElementById('user-avatar-initials').textContent = name.charAt(0).toUpperCase(); document.getElementById('profile-avatar').textContent = name.charAt(0).toUpperCase(); document.getElementById('profile-name').textContent = name; document.getElementById('profile-email').textContent = email || 'user@example.com'; var now = new Date(); document.getElementById('dashboard-date').textContent = now.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }); navigateTo('dashboard'); initChart() }
function logout() { document.getElementById('dashboard-wrapper').classList.add('hidden'); document.getElementById('auth-container').classList.remove('hidden'); document.body.classList.remove('dashboard-active'); closeDropdowns(); showView('login') }
var lE = document.getElementById('login-email'), lP = document.getElementById('login-password'), lEE = document.getElementById('login-email-error'), lPE = document.getElementById('login-password-error');
lE.addEventListener('blur', function () { var v = lE.value.trim(); if (!v) { showError(lEE, 'Email is required'); lE.classList.add('error') } else if (!isValidEmail(v)) { showError(lEE, 'Please enter a valid email'); lE.classList.add('error') } else { hideError(lEE); lE.classList.remove('error') } });
lE.addEventListener('input', function () { hideError(lEE); lE.classList.remove('error') });
lP.addEventListener('blur', function () { var v = lP.value; if (!v) { showError(lPE, 'Password is required'); lP.classList.add('error') } else if (v.length < 6) { showError(lPE, 'Min 6 characters'); lP.classList.add('error') } else { hideError(lPE); lP.classList.remove('error') } });
lP.addEventListener('input', function () { hideError(lPE); lP.classList.remove('error'); updateStrength('login-password', 'login-strength', 'login-strength-fill', 'login-strength-text') });
document.getElementById('login-form').addEventListener('submit', function (e) { e.preventDefault(); var valid = true; var email = lE.value.trim(), pw = lP.value; if (!email) { showError(lEE, 'Email is required'); lE.classList.add('error'); valid = false } else if (!isValidEmail(email)) { showError(lEE, 'Invalid email'); lE.classList.add('error'); valid = false } else { hideError(lEE); lE.classList.remove('error') } if (!pw) { showError(lPE, 'Password is required'); lP.classList.add('error'); valid = false } else if (pw.length < 6) { showError(lPE, 'Min 6 characters'); lP.classList.add('error'); valid = false } else { hideError(lPE); lP.classList.remove('error') } if (!valid) return; var btn = document.getElementById('login-btn'); btn.disabled = true; btn.textContent = 'Signing in...'; setTimeout(function () { btn.disabled = false; btn.textContent = 'Sign In'; document.getElementById('login-success').classList.remove('hidden'); document.getElementById('login-form').reset(); document.getElementById('login-strength').classList.add('hidden'); setTimeout(function () { showDashboard(email) }, 1000) }, 1500) });
var sN = document.getElementById('signup-name'), sE = document.getElementById('signup-email'), sP = document.getElementById('signup-password'), sC = document.getElementById('signup-confirm');
var sNE = document.getElementById('signup-name-error'), sEE = document.getElementById('signup-email-error'), sPE = document.getElementById('signup-password-error'), sCE = document.getElementById('signup-confirm-error');
sN.addEventListener('blur', function () { if (!sN.value.trim()) { showError(sNE, 'Name required'); sN.classList.add('error') } else { hideError(sNE); sN.classList.remove('error') } });
sN.addEventListener('input', function () { hideError(sNE); sN.classList.remove('error') });
sE.addEventListener('blur', function () { var v = sE.value.trim(); if (!v) { showError(sEE, 'Email required'); sE.classList.add('error') } else if (!isValidEmail(v)) { showError(sEE, 'Invalid email'); sE.classList.add('error') } else { hideError(sEE); sE.classList.remove('error') } });
sE.addEventListener('input', function () { hideError(sEE); sE.classList.remove('error') });
sP.addEventListener('blur', function () { if (!sP.value) { showError(sPE, 'Password required'); sP.classList.add('error') } else if (sP.value.length < 6) { showError(sPE, 'Min 6 chars'); sP.classList.add('error') } else { hideError(sPE); sP.classList.remove('error') } });
sP.addEventListener('input', function () { hideError(sPE); sP.classList.remove('error'); updateStrength('signup-password', 'signup-strength', 'signup-strength-fill', 'signup-strength-text') });
sC.addEventListener('blur', function () { if (!sC.value) { showError(sCE, 'Confirm password'); sC.classList.add('error') } else if (sC.value !== sP.value) { showError(sCE, 'Passwords do not match'); sC.classList.add('error') } else { hideError(sCE); sC.classList.remove('error') } });
sC.addEventListener('input', function () { hideError(sCE); sC.classList.remove('error') });
document.getElementById('signup-form').addEventListener('submit', function (e) { e.preventDefault(); var valid = true; if (!sN.value.trim()) { showError(sNE, 'Name required'); sN.classList.add('error'); valid = false } var em = sE.value.trim(); if (!em) { showError(sEE, 'Email required'); sE.classList.add('error'); valid = false } else if (!isValidEmail(em)) { showError(sEE, 'Invalid email'); sE.classList.add('error'); valid = false } if (!sP.value) { showError(sPE, 'Password required'); sP.classList.add('error'); valid = false } else if (sP.value.length < 6) { showError(sPE, 'Min 6 chars'); sP.classList.add('error'); valid = false } if (!sC.value) { showError(sCE, 'Confirm password'); sC.classList.add('error'); valid = false } else if (sC.value !== sP.value) { showError(sCE, 'Mismatch'); sC.classList.add('error'); valid = false } if (!valid) return; var btn = document.getElementById('signup-btn'); btn.disabled = true; btn.textContent = 'Creating...'; setTimeout(function () { btn.disabled = false; btn.textContent = 'Create Account'; document.getElementById('signup-success').classList.remove('hidden'); document.getElementById('signup-form').reset(); document.getElementById('signup-strength').classList.add('hidden'); setTimeout(function () { showView('login') }, 2000) }, 1500) });
var fE = document.getElementById('forgot-email'), fEE = document.getElementById('forgot-email-error');
fE.addEventListener('blur', function () { var v = fE.value.trim(); if (!v) { showError(fEE, 'Email required'); fE.classList.add('error') } else if (!isValidEmail(v)) { showError(fEE, 'Invalid email'); fE.classList.add('error') } else { hideError(fEE); fE.classList.remove('error') } });
fE.addEventListener('input', function () { hideError(fEE); fE.classList.remove('error') });
document.getElementById('forgot-form').addEventListener('submit', function (e) { e.preventDefault(); var em = fE.value.trim(); if (!em) { showError(fEE, 'Email required'); fE.classList.add('error'); return } if (!isValidEmail(em)) { showError(fEE, 'Invalid email'); fE.classList.add('error'); return } var btn = document.getElementById('forgot-btn'); btn.disabled = true; btn.textContent = 'Sending...'; setTimeout(function () { btn.disabled = false; btn.textContent = 'Send Reset Link'; document.getElementById('forgot-success').classList.remove('hidden'); document.getElementById('forgot-form').reset(); setTimeout(function () { document.getElementById('forgot-success').classList.add('hidden') }, 4000) }, 1500) });
function navigateTo(page) { document.querySelectorAll('.page-section').forEach(function (p) { p.classList.remove('active') }); document.getElementById('page-' + page).classList.add('active'); document.querySelectorAll('.sidebar-nav a').forEach(function (a) { a.classList.remove('active') }); var link = document.querySelector('.sidebar-nav a[data-page="' + page + '"]'); if (link) link.classList.add('active'); var titles = { dashboard: 'Dashboard', users: 'Users', analytics: 'Analytics', messages: 'Messages', settings: 'Settings' }; document.getElementById('page-title').textContent = titles[page] || page; document.querySelector('.sidebar').classList.remove('open'); document.querySelector('.sidebar-overlay').classList.remove('open'); closeDropdowns(); if (page === 'analytics') initChart() }
function toggleNotifications(e) { e.stopPropagation(); document.getElementById('profile-dropdown').classList.add('hidden'); document.getElementById('notif-dropdown').classList.toggle('hidden') }
function toggleProfileMenu(e) { e.stopPropagation(); document.getElementById('notif-dropdown').classList.add('hidden'); document.getElementById('profile-dropdown').classList.toggle('hidden') }
function closeDropdowns() { document.getElementById('notif-dropdown').classList.add('hidden'); document.getElementById('profile-dropdown').classList.add('hidden') }
document.addEventListener('click', function () { closeDropdowns() });
function readNotification(el) { el.style.opacity = '0.5'; var badge = document.getElementById('notif-badge'); var c = parseInt(badge.textContent) - 1; if (c <= 0) { badge.style.display = 'none'; c = 0 } badge.textContent = c; showToast('Notification read') }
function markAllRead() { document.querySelectorAll('#notif-dropdown .dropdown-item').forEach(function (i) { i.style.opacity = '0.5' }); document.getElementById('notif-badge').style.display = 'none'; showToast('All notifications read'); closeDropdowns() }
function openModal(id) { document.getElementById(id).classList.add('show'); closeDropdowns() }
function closeModal(id) { document.getElementById(id).classList.remove('show') }
function showToast(msg, isError) { var t = document.createElement('div'); t.className = 'toast' + (isError ? ' error' : ''); t.innerHTML = '<svg viewBox="0 0 24 24"><path d="' + (isError ? 'M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z' : 'M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z') + '"/></svg>' + msg; document.body.appendChild(t); setTimeout(function () { t.style.opacity = '0'; t.style.transition = 'opacity 0.3s'; setTimeout(function () { t.remove() }, 300) }, 3000) }
function addUser() { var name = document.getElementById('new-user-name').value.trim(); var email = document.getElementById('new-user-email').value.trim(); var role = document.getElementById('new-user-role').value; if (!name || !email) { showToast('Fill all fields', true); return } if (!isValidEmail(email)) { showToast('Invalid email', true); return } var tbody = document.querySelector('#users-table tbody'); var tr = document.createElement('tr'); var today = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }); tr.innerHTML = '<td>' + name + '</td><td>' + email + '</td><td>' + role + '</td><td><span class="status-badge active">Active</span></td><td>' + today + '</td>'; tbody.insertBefore(tr, tbody.firstChild); closeModal('add-user-modal'); document.getElementById('new-user-name').value = ''; document.getElementById('new-user-email').value = ''; showToast('User "' + name + '" added!'); addActivity('blue', 'New user added', name + ' (' + role + ')') }
function filterUsers() { var q = document.getElementById('user-search').value.toLowerCase(); document.querySelectorAll('#users-table tbody tr').forEach(function (r) { r.style.display = r.textContent.toLowerCase().includes(q) ? '' : 'none' }) }
function filterMessages() { var q = document.getElementById('msg-search').value.toLowerCase(); document.querySelectorAll('#msg-list .msg-item').forEach(function (m) { m.style.display = m.textContent.toLowerCase().includes(q) ? '' : 'none' }) }
function generateReport() { var type = document.getElementById('report-type').value; var range = document.getElementById('report-range').value; closeModal('report-modal'); showToast(type + ' generating...'); setTimeout(function () { showToast(type + ' ready!') }, 2000); addActivity('green', 'Report generated', type + ' (' + range + ')') }
function sendNewsletter() { var subj = document.getElementById('nl-subject').value.trim(); var msg = document.getElementById('nl-message').value.trim(); if (!subj || !msg) { showToast('Fill subject & message', true); return } var r = document.getElementById('nl-recipients').value; closeModal('newsletter-modal'); document.getElementById('nl-subject').value = ''; document.getElementById('nl-message').value = ''; showToast('Newsletter sent to ' + r + '!'); addActivity('orange', 'Newsletter sent', '"' + subj + '"') }
function sendMessage() { var to = document.getElementById('compose-to').value.trim(); var subj = document.getElementById('compose-subject').value.trim(); var body = document.getElementById('compose-body').value.trim(); if (!to || !subj || !body) { showToast('Fill all fields', true); return } closeModal('compose-modal'); document.getElementById('compose-to').value = ''; document.getElementById('compose-subject').value = ''; document.getElementById('compose-body').value = ''; showToast('Message sent to ' + to + '!'); addActivity('blue', 'Message sent', 'To ' + to) }
function openMsgModal(sender, body, time) { document.getElementById('view-msg-sender').textContent = sender; document.getElementById('view-msg-body').textContent = body; document.getElementById('view-msg-time').textContent = time; openModal('view-msg-modal') }
function changePassword() { var cur = document.getElementById('pw-current').value; var nw = document.getElementById('pw-new').value; var cf = document.getElementById('pw-confirm').value; if (!cur || !nw || !cf) { showToast('Fill all fields', true); return } if (nw.length < 6) { showToast('Min 6 characters', true); return } if (nw !== cf) { showToast('Passwords do not match', true); return } closeModal('change-pw-modal'); document.getElementById('pw-current').value = ''; document.getElementById('pw-new').value = ''; document.getElementById('pw-confirm').value = ''; showToast('Password changed!') }
function addActivity(color, title, desc) { var feed = document.getElementById('activity-feed'); var item = document.createElement('div'); item.className = 'activity-item'; item.style.animation = 'fadeIn 0.3s ease-out'; item.innerHTML = '<div class="activity-dot ' + color + '"></div><div><div class="activity-text"><strong>' + title + '</strong> &mdash; ' + desc + '</div><div class="activity-time">Just now</div></div>'; feed.insertBefore(item, feed.firstChild); if (feed.children.length > 10) feed.removeChild(feed.lastChild) }
function initChart() { var chart = document.getElementById('revenue-chart'); if (!chart || chart.children.length > 0) return; var data = [{ l: 'Mon', v: 65, c: '#667eea' }, { l: 'Tue', v: 80, c: '#764ba2' }, { l: 'Wed', v: 45, c: '#667eea' }, { l: 'Thu', v: 90, c: '#764ba2' }, { l: 'Fri', v: 70, c: '#667eea' }, { l: 'Sat', v: 55, c: '#764ba2' }, { l: 'Sun', v: 85, c: '#667eea' }]; data.forEach(function (d) { var bar = document.createElement('div'); bar.className = 'chart-bar'; bar.style.background = d.c; bar.style.height = '0%'; bar.innerHTML = '<div class="bar-value">$' + Math.round(d.v * 543) + '</div><div class="bar-label">' + d.l + '</div>'; chart.appendChild(bar); setTimeout(function () { bar.style.height = d.v + '%' }, 100) }) }
